version: '3'
services:
  fe:
    image: 815345612430.dkr.ecr.ap-south-1.amazonaws.com/punumflutes/fe:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - SECRET_TOKEN=secrettoken
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=6LdeggYaAAAAAK2RPUpCMhHEAuCxB0M0YLeLEVYC
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=461111854902-m63bo0r7meps3te3pg91krgvmlesesbo.apps.googleusercontent.com

  be:
    image: 815345612430.dkr.ecr.ap-south-1.amazonaws.com/punumflutes/be
    ports:
      - '8000:8000'
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"

